'use strict';
// Runs a script generated by zotero_pdf_text.bibtex against a fake `Zotero` global, the way the
// debug-bridge plugin does: `new AsyncFunction('query', body)`, then JSON.stringify of the result
// (retorquere/zotero-better-bibtex test/fixtures/debug-bridge/bootstrap.js).
//
//   node fake_zotero.js <scenario.json> <script.js>
//
// The scenario carries `env` (tests/fixtures/zotero_bridge/zotero_env.json, prefs exactly as
// recorded -- allowed_fileext stays a JSON *string*) plus the case's library state. Time is
// virtual: Zotero.Promise.delay advances a clock that Date.now reads, and fires any fake ZotMoov
// move that has come due, so a 13 s wait finishes instantly.
//
// Prints {response, elapsedMs, children} where children is the parent's attachments at the end.

const fs = require('fs');

const [scenarioPath, scriptPath] = process.argv.slice(2);
const scenario = JSON.parse(fs.readFileSync(scenarioPath, 'utf8'));
const code = fs.readFileSync(scriptPath, 'utf8');
const env = scenario.env;

// Zotero.Attachments.LINK_MODE_* (chrome/content/zotero/xpcom/attachments.js). The recorded env
// holds the first three; LINKED_URL is taken from the source because isFileAttachment needs it.
const LINK_MODE_IMPORTED_FILE = env.linkModes.LINK_MODE_IMPORTED_FILE;
const LINK_MODE_IMPORTED_URL = env.linkModes.LINK_MODE_IMPORTED_URL;
const LINK_MODE_LINKED_FILE = env.linkModes.LINK_MODE_LINKED_FILE;
const LINK_MODE_LINKED_URL = 3;

// ---- virtual clock -------------------------------------------------------------------------
const START = 1700000000000;
let now = START;
const timers = [];
Date.now = () => now;
function schedule(delayMs, fn) {
    timers.push({ at: now + delayMs, fn });
}
function advance(ms) {
    const target = now + ms;
    for (;;) {
        timers.sort((a, b) => a.at - b.at);
        if (!timers.length || timers[0].at > target) {
            break;
        }
        const timer = timers.shift();
        now = Math.max(now, timer.at);
        timer.fn();
    }
    now = target;
}

// ---- items -----------------------------------------------------------------------------------
let nextId = 100;
const items = new Map();
function addItem(fields) {
    const item = Object.assign({ id: nextId++ }, fields);
    items.set(item.id, item);
    return item;
}
function addAttachment(parent, spec) {
    return addItem({
        key: spec.key,
        parentID: parent.id,
        attachmentLinkMode: spec.linkMode,
        attachmentContentType: spec.contentType,
        _path: spec.path,
        isFileAttachment() {
            return this.attachmentLinkMode !== LINK_MODE_LINKED_URL;
        },
        getFilePath() {
            return this._path;
        },
    });
}
function addRegularItem(spec) {
    return addItem({
        key: spec.key,
        itemTypeID: spec.itemTypeID,
        _title: spec.title || '',
        getField(name) {
            if (name !== 'title') {
                throw new Error('fake item has no field ' + name);
            }
            return this._title;
        },
        getAttachments() {
            const self = this;
            return Array.from(items.values()).filter((i) => i.parentID === self.id).map((i) => i.id);
        },
    });
}

const parent = scenario.parent ? addRegularItem(scenario.parent) : null;
for (const spec of scenario.existingAttachments || []) {
    addAttachment(parent, spec);
}

// ---- prefs, as recorded ----------------------------------------------------------------------
const prefs = Object.assign({}, env.zotmoovPrefs, scenario.prefOverrides || {});
if ('dst_dir_set' in prefs) {
    if (!('dst_dir' in prefs)) {
        prefs.dst_dir = prefs.dst_dir_set ? '/fake/zotmoov/destination' : '';
    }
    delete prefs.dst_dir_set;
}
const PREF_PREFIX = 'extensions.zotmoov.';

// ---- fake ZotMoov: auto-move after auto_process_delay, under its own conditions ----------------
function extensionOf(path) {
    const leaf = String(path).split(/[\\/]/).pop();
    const pos = leaf.lastIndexOf('.');
    return pos === -1 ? '' : leaf.substr(pos + 1);
}
function zotmoovWouldMove(attachment) {
    let allowed = [];
    try {
        allowed = JSON.parse(prefs.allowed_fileext || '[]');
    } catch (e) {
        allowed = [];
    }
    const path = attachment.getFilePath();
    return !!prefs.enable_automove
        && prefs.file_behavior === 'move'
        && !!prefs.dst_dir
        && !!path
        && attachment.attachmentLinkMode !== LINK_MODE_LINKED_FILE
        && (!allowed.length || allowed.map((x) => String(x).toLowerCase())
            .indexOf(extensionOf(path).toLowerCase()) !== -1);
}
function queueAutoMove(attachment) {
    if (!env.zotmoov || scenario.zotmoovStalls || !zotmoovWouldMove(attachment)) {
        return;
    }
    schedule(Number(prefs.auto_process_delay), () => {
        items.delete(attachment.id);
        addAttachment(parent, {
            key: scenario.movedKey,
            linkMode: LINK_MODE_LINKED_FILE,
            contentType: attachment.attachmentContentType,
            path: '/fake/zotmoov/destination/' + String(attachment.getFilePath()).split(/[\\/]/).pop(),
        });
    });
}

// ---- the Zotero global -----------------------------------------------------------------------
class FakeSearchTranslate {
    setIdentifier(identifier) {
        this.identifier = identifier;
    }
    async getTranslators() {
        return (scenario.translate && scenario.translate.translators) || [];
    }
    setTranslator(translators) {
        this.translators = translators;
    }
    async translate() {
        return ((scenario.translate && scenario.translate.items) || []).map(addRegularItem);
    }
}

globalThis.Zotero = {
    version: env.zoteroVersion,
    Libraries: { userLibraryID: 1 },
    Prefs: {
        get(name, global) {
            if (global !== true || !name.startsWith(PREF_PREFIX)) {
                throw new Error('unexpected pref read ' + name + ' (global=' + global + ')');
            }
            return prefs[name.slice(PREF_PREFIX.length)];
        },
    },
    ItemTypes: {
        getName(id) {
            const name = env.itemTypeNames[String(id)];
            if (!name) {
                throw new Error('unknown item type id ' + id);
            }
            return name;
        },
    },
    File: {
        getExtension: extensionOf,
    },
    Promise: {
        delay(ms) {
            advance(ms);
            return Promise.resolve();
        },
    },
    Items: {
        async getAsync(ids) {
            if (!Array.isArray(ids)) {
                return items.get(ids) || false;
            }
            return ids.map((id) => items.get(id)).filter(Boolean);
        },
        exists(id) {
            return items.has(id);
        },
        async getByLibraryAndKeyAsync(libraryID, key) {
            for (const item of items.values()) {
                if (item.key === key) {
                    return item;
                }
            }
            return false;
        },
    },
    Attachments: {
        LINK_MODE_IMPORTED_FILE,
        LINK_MODE_IMPORTED_URL,
        LINK_MODE_LINKED_FILE,
        LINK_MODE_LINKED_URL,
        async addAvailableFile(item) {
            advance(scenario.downloadMs || 0);
            if (!scenario.found) {
                return null;
            }
            const attachment = addAttachment(item, scenario.attachment);
            queueAutoMove(attachment);
            return attachment;
        },
        addAvailablePDF(item) {
            return this.addAvailableFile(item);
        },
    },
    Translate: { Search: FakeSearchTranslate },
    ZotMoov: env.zotmoov ? {} : undefined,
};

const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;
(async () => {
    const action = new AsyncFunction('query', code);
    let response = await action({});
    if (typeof response === 'undefined') {
        response = null;
    }
    const children = parent
        ? parent.getAttachments().map((id) => {
            const a = items.get(id);
            return { key: a.key, linkMode: a.attachmentLinkMode };
        })
        : [];
    process.stdout.write(JSON.stringify({
        response: JSON.parse(JSON.stringify(response)),
        elapsedMs: now - START,
        children,
    }));
})().catch((err) => {
    process.stderr.write(String(err && err.stack ? err.stack : err));
    process.exit(1);
});
